---
title: modulusx.github.io
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Matt Kunkel
description: What am I doing?
avatar: http://www.gravatar.com/avatar/2c45ea211d0d32a146557573d8cd1e75
footer-links:
  dribbble: 
  email: matt@mrkunkel.com
  facebook: 
  flickr: 
  github: modulusx
  instagram: 
  linkedin: mrkunkel
  pinterest: 
  rss: 
  twitter: modulusx
  stackoverflow: 
  youtube: user/XsuludoM
  googleplus: "+ModulusX"
disqus: 
google_analytics: 
url: http://blog.mrkunkel.com
baseurl: 
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
